version: "3.8"
services:
  rest-server:
    build:
      context: .
    depends_on:
      mariadb:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - '8080:8080'
  mariadb:
    image: mariadb
    volumes:
      - ./sql-scripts/:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    healthcheck:
      test: "/usr/bin/mysql --user=$MARIADB_USER --password=$MARIADB_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
    env_file: .env
    restart: always
